### ISSUE TITLE
Token Not Valid

### ISSUE THREAD

**Issue by fahmy554** [unfuncaptcha/tguess#3]
when i use requests to generate funcaptcha tokens

site not accept it although arkose labs tells me 
solved is true 
i dont know why?

**Comment by spearphishing** [comment]
![telegram-cloud-photo-size-2-5399832029736067745-y](https://github.com/unfuncaptcha/tguess/assets/135459773/000bdcd7-b06d-443b-9cdf-bfa18baae4cf)

This package generates 1:1 guess/tguess components, verified from actual FunCaptcha tguesses (tested 2 days ago due to someone else having a problem with their solver), so you must be doing something else wrong in your solving system.

**Comment by kekeds** [comment]
> This package generates 1:1 guess/tguess components,

No it does NOT generate 1:1 tguess. the tguess generated is wrong and will always get rejected. i reversed it myself and it works so fuck you

**Comment by spearphishing** [comment]
How is it wrong exactly

**Comment by spearphishing** [comment]
The script's 3 months old buddy, looking into it now.

**Comment by spearphishing** [comment]
[![tguess example video](https://github.com/user-attachments/assets/e5dee7e8-2234-4187-8c71-c41a2822cbd1)](https://www.youtube.com/watch?v=mG7CLC504d8 "tguess example video")

Tested with outlook, seems to work fine.


> On the topic of flags, your discord joiner is flagged. Stick to fake token generators for now.
